name: update dependencies
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"
jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
    - uses: actions/setup-go@v5
    - name: NPM dependencies
      run: |
        cd frontend
        npx npm-check-updates -x /^@typescript-eslint.*$/ -u && npm i
        npm run build && rm -rf ./app
    - name: Go dependencies
      run: |
        cd backend
        go mod tidy && go get -u
        go build -o app . && rm -rf ./app
    - uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "feat: bump deps"
        branch: "update-deps"
        title: "feat: bump deps"
        labels: automated pr
        assignees: lafin
        reviewers: lafin
