name: update dependencies
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"
jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-go@v2
    - name: NPM dependencies
      run: cd frontend && npx npm-check-updates -u && npm i
    - name: Go dependencies
      run: cd backend && go mod tidy && go get -u
    - uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update dependencies
        branch: "update_deps"
        title: Update dependencies
